services:
  python:
    build: .
    volumes:
      - ./:/var/www/
    command: "/var/www/bin/run.sh"
  db:
    image: postgres
    ports:
      -42069:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust